
const tableNames = require('../../utils/constants/tableNames');


exports.seed = async knex => {

    try {
        //delete data
        await knex(tableNames.properties).del();

        //create new table
        await knex(tableNames.properties).insert([
            {
                title: 'Central Park House',
                slug: 'central-park-house',
                description: 'Central Park is an urban park in New York City located between the Upper West and Upper East Sides of Manhattan.',
                address: 'Central Park',
                city: 'New York',
                state: 'NY',
                zipcode: '10028',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603128/airspace/properties/house-1_subjva.jpg',
                bedrooms: 3,
                bathrooms: 5,
                guests: 10,
                price: 250.00,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43316',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'Rockefeller Center House',
                slug: 'rockefeller-center-house',
                description: 'Rockefeller Center is a large complex consisting of 19 commercial buildings covering 22 acres between 48th Street and 51st Street in Midtown Manhattan, New York City.',
                address: '45 Rockefeller Plaza',
                city: 'New York',
                state: 'NY',
                zipcode: '10111',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603130/airspace/properties/house-2_oxucuq.jpg',
                bedrooms: 5,
                bathrooms: 7,
                guests: 12,
                price: 1200.00,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43316',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'Empire State Building House',
                slug: 'empire-state-building-house',
                description: 'The Empire State Building is a 102-story Art Deco skyscraper in Midtown Manhattan in New York City.',
                address: '20 W 34th St',
                city: 'New York',
                state: 'NY',
                zipcode: '10001',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603133/airspace/properties/house-3_bsolra.jpg',
                bedrooms: 5,
                bathrooms: 2,
                guests: 8,
                price: 750.56,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43316',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'Arlo SoHo',
                slug: 'arlo-soho',
                description: 'In the heart of one of the coolest spaces in the city',
                address: '31 Hudson St',
                city: 'New York',
                state: 'NY',
                zipcode: '10013',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603134/airspace/properties/house-4_fw45wu.jpg',
                bedrooms: 9,
                bathrooms: 2,
                guests: 16,
                price: 1450.75,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43316',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'The Langham',
                slug: 'the-langham',
                description: 'Elegant hotel offering rooms & suites with understated decor, plus a spa, a gym & fine dining.',
                address: '400 5th Ave',
                city: 'New York',
                state: 'NY',
                zipcode: '10018',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603124/airspace/properties/house-5_aufllg.jpg',
                bedrooms: 7,
                bathrooms: 2,
                guests: 15,
                price: 1800.50,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43316',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'Walt Disney World Parks Hotel',
                slug: 'walt-disney-world-parks-hotel',
                description: 'he Walt Disney World Resort, also called Walt Disney World and Disney World, is an entertainment complex in Bay Lake and Lake Buena Vista, Florida, in the United States, near the cities of Orlando and Kissimmee.',
                address: '1375 E Buena Vista',
                city: 'Orlando',
                state: 'FL',
                zipcode: '32830',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603126/airspace/properties/house-6_bhf6na.jpg',
                bedrooms: 3,
                bathrooms: 5,
                guests: 10,
                price: 300.00,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43317',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'Universal Orlando Resort',
                slug: 'universal-orlando-resort',
                description: 'American theme park and entertainment resort complex based in Orlando, Florida.',
                address: '6000 Universal Blvd',
                city: 'Orlando',
                state: 'FL',
                zipcode: '32819',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603307/airspace/properties/house-7_rtp7rl.jpg',
                bedrooms: 13,
                bathrooms: 8,
                guests: 20,
                price: 1500.15,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43317',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'SeaWorld Orlando',
                slug: 'seaworld-orlando',
                description: 'SeaWorld Orlando is a theme park and marine zoological park, in Orlando, Florida. It is owned and operated by SeaWorld Parks & Entertainment.',
                address: '7007 Sea World Dr',
                city: 'Orlando',
                state: 'FL',
                zipcode: '32821',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603305/airspace/properties/house-8_vtepzg.jpg',
                bedrooms: 3,
                bathrooms: 2,
                guests: 5,
                price: 750.70,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43317',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'The Grove Resort',
                slug: 'the-grove-resort',
                description: 'Sanctuary from the lively pace of neighboring theme parks.',
                address: '14501 Grove Resort Ave',
                city: 'Orlando',
                state: 'FL',
                zipcode: '34787',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603303/airspace/properties/house-9_th03t8.jpg',
                bedrooms: 3,
                bathrooms: 2,
                guests: 5,
                price: 1150.50,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43317',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'Caribe Royale',
                slug: 'caribe-royale',
                description: 'Enjoy luxury hotel and suites at Caribe Royale Orlando',
                address: '7007 Sea World Dr',
                city: 'Orlando',
                state: 'FL',
                zipcode: '32821',
                propertyImage: 'https://res.cloudinary.com/airspacerental/image/upload/v1610603301/airspace/properties/house-10_tlcrjk.jpg',
                bedrooms: 4,
                bathrooms: 3,
                guests: 7,
                price: 650.50,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43317',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            // GOT TO HERE
            {
                title: 'Fremont Street Experience Hotel',
                slug: 'fremont-street-experience-hotel',
                description: 'The Fremont Street Experience is a pedestrian mall and attraction in downtown Las Vegas, Nevada.',
                address: 'Fremont St',
                city: 'Las Vegas',
                state: 'NV',
                zipcode: '89101',
                propertyImage: '',
                bedrooms: 4,
                bathrooms: 3,
                guests: 7,
                price: 350.10,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43318',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: 'Paris Hotel and the Eiffel Tower',
                slug: 'paris-hotel-and-the-eiffel-tower',
                description: 'Paris Las Vegas is one of the most easily recognized resorts in the city. Out front is a scale model of the Eiffel Tower, and down the way is a recreation of the Paris Opera House.',
                address: '3655 S Las Vegas Blvd',
                city: 'Las Vegas',
                state: 'NV',
                zipcode: '89101',
                propertyImage: '',
                bedrooms: 8,
                bathrooms: 6,
                guests: 15,
                price: 1550.00,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43318',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
            {
                title: `Caesar's Palace`,
                slug: 'caesars-palace',
                description: `Currently Caesar's Palace is a massive complex in the middle of the Strip, complete with every imaginable entertainment option.`,
                address: '3570 S Las Vegas Blvd',
                city: 'Las Vegas',
                state: 'NV',
                zipcode: '89101',
                propertyImage: '',
                bedrooms: 10,
                bathrooms: 8,
                guests: 25,
                price: 950.15,
                userId: '156fb36e-8973-45f1-8e1f-30bb1cd43318',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString()
            },
        ]);

    } catch (error) {
        console.log('Something went wrong with properties seeding');
        console.log(error);
    }
};

